= Cheatsheets

[[ServiceOptions]]
== ServiceOptions

++++
 Allows a vert.x application to customize the registration of a service.
 Future extension point to add more options.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[initialCapacity]]`initialCapacity`|`Number (int)`|-
|===

[[OutgoingLinkOptions]]
== OutgoingLinkOptions

++++
 Allows a vert.x application to customize the establishing of an outgoing
 link. Reliability are supported and recovery options in a future release.
 Future extension point to add more options.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[recoveryOptions]]`recoveryOptions`|`link:dataobjects.html#RetryOptions[RetryOptions]`|-
|[[reliability]]`reliability`|`link:enums.html#ReliabilityMode[ReliabilityMode]`|
+++
Please see link to understand the reliability modes
 and it's implications.
+++
|===

[[RetryOptions]]
== RetryOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[alternativeAddressList]]`alternativeAddressList`|`Array of String`|-
|[[maxRetryInterval]]`maxRetryInterval`|`Number (long)`|-
|[[maxRetryLimit]]`maxRetryLimit`|`Number (int)`|-
|[[minRetryInterval]]`minRetryInterval`|`Number (long)`|-
|[[retryPolicy]]`retryPolicy`|`link:enums.html#RetryPolicy[RetryPolicy]`|-
|===

[[IncomingLinkOptions]]
== IncomingLinkOptions

++++
 Allows a vert.x application to customize the establishing of an incoming link.
 Prefetch and reliability are supported and recovery options in a future
 release. Future extension point to add more options.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[prefetch]]`prefetch`|`Number (int)`|
+++
<i>Defaults to "1". </i><br>
 <i>If set to a value > 0 </i>, the Vert.x-AMQP-Service will automatically
 fetch more messages when a certain number of messages are marked as
 either accepted, rejected or released. The Vert.x-AMQP-Service will
 determine the optimum threshold for when the fetch happens and how much
 to fetch. <br>
 <i>If set to "zero"</i>, the vert.x application will need to explicitly
 request messages using
 link
+++
|[[recoveryOptions]]`recoveryOptions`|`link:dataobjects.html#RetryOptions[RetryOptions]`|-
|[[reliability]]`reliability`|`link:enums.html#ReliabilityMode[ReliabilityMode]`|-
|===

